apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: my-nginx1
spec:
  selector:
    matchLabels:
      app: my-nginx1
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
